data <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, colClasses = "character", na.strings = "?", skip = 66636, nrows = 2880)
headerVal <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, colClasses = "character", na.strings = "?",nrows = 1)
names(data) <- names(headerVal)
data$combineDate <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
plot(data$combineDate, data$Sub_metering_1, xaxt='n', type = "l", 
     xlab = "",ylab='Global Active Power (kilowatts)', col = "black")
lines(data$combineDate, data$Sub_metering_2, col = "red")
lines(data$combineDate, data$Sub_metering_3, col = "blue")
axis.POSIXct(1, data$combineDate, format="%a")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black", "red", "blue"), lty = 1)
dev.copy(png,"plot3.png", width = 480, height = 480)
dev.off()